name: Generate API Client

on:
  #push:
  #  branches:
  #    - main # Update this based on your branch name
  workflow_dispatch:

jobs:
  generate-api-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK (if using a Java-based generator)
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install OpenAPI Generator
      run: |
        #wget https://github.com/OpenAPITools/openapi-generator-cli/releases/download/v5.3.0/openapi-generator-cli-5.3.0.jar
        wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.1.0/openapi-generator-cli-7.1.0.jar
        chmod +x openapi-generator-cli-7.1.0.jar
        mv openapi-generator-cli-7.1.0.jar /usr/local/bin/openapi-generator.jar

    - name: Generate API Client
      run: |
        #java -jar /usr/local/bin/openapi-generator.jar generate -i schema.yaml -g php -o generated-client
        java -jar /usr/local/bin/openapi-generator.jar generate \
         -i schema.yaml -g php \
         --additional-properties composerPackageName='itsmind/sevdesk-php-client' \
         --invoker-package 'Itsmind\\Sevdesk' \
         -o .

    - name: Commit Generated Code
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        #git add generated-client
        git add --all
        git commit -m "Update generated API client" || true
        git push
